SELECT
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM
    SUBWAY_DISTANCE
GROUP BY
    ROUTE
ORDER BY 
    SUM(D_BETWEEN_DIST) DESC

-- 정렬 기준을 'TOTAL_DISTANCE'로 하면 오답이 나온다. 'km'가 붙으면서 문자열 정렬이 되기 때문이다.
