-- BEFORE
SELECT 
    F.FLAVOR
FROM
    FIRST_HALF F
JOIN 
    (SELECT FLAVOR, 
     SUM(TOTAL_ORDER) JSUM
     FROM JULY
     GROUP BY FLAVOR) J
ON
    F.FLAVOR = J.FLAVOR
GROUP BY
    F.FLAVOR
ORDER BY 
    JSUM + SUM(F.TOTAL_ORDER) desc
LIMIT 3

-- AFTER
SELECT FLAVOR
FROM
    (SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM JULY) TBL
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
